{% set name = "handsontable" %}
{% set version = "8.0.0" %}
{% set sha256 = "795fbf6d3dfaae20e911d7eb463ad8b77046b2d92b8fa31212b71dc6f8c0de2c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/handsontable/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs

test:
  commands:
    - npm list -g handsontable
  requires:
    - nodejs


about:
  home: https://github.com/handsontable/handsontable
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Handsontable Community Edition - JavaScript/HTML5 Spreadsheet Component for Web Apps
  description: |
    Handsontable Community Edition (CE) is an open source JavaScript/HTML5 UI Spreadsheet 
    component for web apps. It easily integrates with any data source and comes with a 
    variety of useful features like data binding, validation, sorting or powerful context 
    menu. Actively supported by the Handsoncode team and many contributors. 
  doc_url: https://docs.handsontable.com
  dev_url: https://github.com/handsontable/handsontable
