{% set name = "handsontable" %}
{% set version = "7.1.1" %}
{% set sha256 = "96c862a728bca5b7640349c84228a0713a13a1ef463525469ebd73b39913c3a7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/handsontable/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g handsontable
  requires:
    - nodejs
   

about:
  home: https://github.com/handsontable/handsontable
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Handsontable Community Edition - JavaScript/HTML5 Spreadsheet Component for Web Apps'
  description: |
    Handsontable Community Edition (CE) is an open source JavaScript/HTML5 UI Spreadsheet 
    component for web apps. It easily integrates with any data source and comes with a 
    variety of useful features like data binding, validation, sorting or powerful context 
    menu. Actively supported by the Handsoncode team and many contributors. 
  doc_url: https://docs.handsontable.com
  dev_url: https://github.com/handsontable/handsontable

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
