travis:
  secure:
    BINSTAR_TOKEN: iYOzqwsKCGIWVIJY8LSjfS8dbG1453vepbxNftAYEi7TcEJ20mi40XskNqJytIuVLBgd1mrYrIFWMvulsWGxeT/7bhVd6/RpTyZAXbJ+pShQr/Doq1auTgdtECR/VYvx972+GF0b+D76cFdXl+k9SCWKB9YO4t33/lK8z++rE1Ads4AgI/gSprGiHsAe4bpTzyElbfwc9U7tPrH6oB7rKAxjQv3m3Dp/TlLgM3LWPHRkqQg23dQrDwpwoAntkTEZ2ordeQvP2n+a5CRypiksMn59WMZNt+LJULxPf3Rx6ZE7jdk9oe1Gtw4LDo/qRYCoYVUjHtdqzWdhBLDAAc2XJvEu4fBscPPV29FNJJgHfHQ8HOZPxLb0AhQCkWbDvqfaJ+mlA/j4kdKu/z2I6j6Im+0xI9FfpOFWs40p7/njk5lOjsRqY4quxfKCH0wMwSJlaXU9kMl0wjXC8zxsKuIIzzvwwGLTgjmZnYh9rfoPiQYV6G5TnFYVcXsW1HSRhplO/PjODkyRm97El6DVa5ACjytowLtS8MMkjJ449w2MYqgZUT0VcjWjolcR6yUxRdrl+vx0vqA1vnogbFCDZPGAPXzG+WaEVxb4vrKihNlbZdrc+jWUvoew5syxMIE27u/0rgrIXU+SZJpHkadtyVwfc4n5vE4e1XIhG4RQGSk28wo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
