travis:
  secure:
    BINSTAR_TOKEN: rBKSK2gImUEpw6QGAHH0rPKqa0ntY9gaFBWNUj5msNFlVtpmVGiMUao5VXhd9DEGqJ3gG6j8smsvs14t9BIL3ksF8hJBurN9Z7IiCjFiszl18Ak93rvTF4hcxCZD1pwNGbpNspvgS71NdiK5fnppUbBIhuoO4lV4/WnhSr9eFeP8KMvQAsXQJFL580/nUXy73xaoEUz38mWH0nPEqFC0esiJ5TlCdSENYFJk+wfDYJkQI9Vd58ICDAvV+wT8rs1DJXtCd1RHK+zx5DGsjz14s9yog9ebS7mY5+Vp27T6IovIMj/sr3MLhLjwaOWFW3UXlsqTXA9uST3RO/7r3IrDaojLqlZkFH4ES0jj2zHEyHmdTJ9C9DUxGl7udQmVGz700L8i64pTSwPqXEXnGkBO6pDbLaK7Rrm6SkosoQAyxjBXfHLRtIL9iIN2abn3YwKT5QXZtgu3iHztPRhwji5fgqPK+5UzZZe/4hD1Hs5kL/IBOW0KC/PU7ksrNPsLbtFe3t6QFH0jhEnf4431D7YydQTfHxeFw40SPZnIi2Or3iD+/ckcDbcON7kkPuApSGWuibUoWkOrDk5FJUUQdfhDGa7bhUpfJQKYutAketm9EnvykjLMmoU+CpI5IDpIBIYwamTnsqghAlAEvQTjnAcmE1zw8lLVA1jMCtjJLxV5KjM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
